-- STEP 1
DATES
1 'JAN' 1991 /
/
 
-- STEP 2
DATES
11 'JAN' 1991 /
/
 
-- STEP 3
DATES
21 'JAN' 1991 /
/
 
-- STEP 4
DATES
31 'JAN' 1991 /
/
 
-- STEP 5
DATES
10 'FEB' 1991 /
/
 
-- STEP 6
DATES
20 'FEB' 1991 /
/
 
-- STEP 7
DATES
2 'MAR' 1991 /
/
 
-- STEP 8
DATES
12 'MAR' 1991 /
/
 
-- STEP 9
DATES
22 'MAR' 1991 /
/
 
-- STEP 10
DATES
1 'APR' 1991 /
/
 
-- STEP 11
DATES
11 'APR' 1991 /
/
 
-- STEP 12
DATES
21 'APR' 1991 /
/
 
-- STEP 13
DATES
1 'MAY' 1991 /
/
 
-- STEP 14
DATES
11 'MAY' 1991 /
/
 
-- STEP 15
DATES
21 'MAY' 1991 /
/
 
-- STEP 16
DATES
31 'MAY' 1991 /
/
 
-- STEP 17
DATES
10 'JUN' 1991 /
/
 
-- STEP 18
DATES
20 'JUN' 1991 /
/
 
-- STEP 19
DATES
30 'JUN' 1991 /
/
 
-- STEP 20
DATES
10 'JUL' 1991 /
/
 
-- STEP 21
DATES
20 'JUL' 1991 /
/
 
-- STEP 22
DATES
30 'JUL' 1991 /
/
 
-- STEP 23
DATES
9 'AUG' 1991 /
/
 
-- STEP 24
DATES
19 'AUG' 1991 /
/
 
-- STEP 25
DATES
29 'AUG' 1991 /
/
 
-- STEP 26
DATES
8 'SEP' 1991 /
/
 
-- STEP 27
DATES
18 'SEP' 1991 /
/
 
-- STEP 28
DATES
28 'SEP' 1991 /
/
 
-- STEP 29
DATES
8 'OCT' 1991 /
/
 
-- STEP 30
DATES
18 'OCT' 1991 /
/
 
-- STEP 31
DATES
28 'OCT' 1991 /
/
 
-- STEP 32
DATES
7 'NOV' 1991 /
/
 
-- STEP 33
DATES
17 'NOV' 1991 /
/
 
-- STEP 34
DATES
27 'NOV' 1991 /
/
 
-- STEP 35
DATES
7 'DEC' 1991 /
/
 
-- STEP 36
DATES
17 'DEC' 1991 /
/
 
-- STEP 37
DATES
27 'DEC' 1991 /
/
 
-- STEP 38
DATES
6 'JAN' 1992 /
/
 
-- STEP 39
DATES
16 'JAN' 1992 /
/
 
-- STEP 40
DATES
26 'JAN' 1992 /
/
 
-- STEP 41
DATES
5 'FEB' 1992 /
/
 
-- STEP 42
DATES
15 'FEB' 1992 /
/
 
-- STEP 43
DATES
25 'FEB' 1992 /
/
 
-- STEP 44
DATES
6 'MAR' 1992 /
/
 
-- STEP 45
DATES
16 'MAR' 1992 /
/
 
-- STEP 46
DATES
26 'MAR' 1992 /
/
 
-- STEP 47
DATES
5 'APR' 1992 /
/
 
-- STEP 48
DATES
15 'APR' 1992 /
/
 
-- STEP 49
DATES
25 'APR' 1992 /
/
 
-- STEP 50
DATES
5 'MAY' 1992 /
/
 
-- STEP 51
DATES
15 'MAY' 1992 /
/
 
-- STEP 52
DATES
25 'MAY' 1992 /
/
 
-- STEP 53
DATES
4 'JUN' 1992 /
/
 
-- STEP 54
DATES
14 'JUN' 1992 /
/
 
-- STEP 55
DATES
24 'JUN' 1992 /
/
 
-- STEP 56
DATES
4 'JUL' 1992 /
/
 
-- STEP 57
DATES
14 'JUL' 1992 /
/
 
-- STEP 58
DATES
24 'JUL' 1992 /
/
 
-- STEP 59
DATES
3 'AUG' 1992 /
/
 
-- STEP 60
DATES
13 'AUG' 1992 /
/
 
-- STEP 61
DATES
23 'AUG' 1992 /
/
 
-- STEP 62
DATES
2 'SEP' 1992 /
/
 
-- STEP 63
DATES
12 'SEP' 1992 /
/
 
-- STEP 64
DATES
22 'SEP' 1992 /
/
 
-- STEP 65
DATES
2 'OCT' 1992 /
/
 
-- STEP 66
DATES
12 'OCT' 1992 /
/
 
-- STEP 67
DATES
22 'OCT' 1992 /
/
 
-- STEP 68
DATES
1 'NOV' 1992 /
/
 
-- STEP 69
DATES
11 'NOV' 1992 /
/
 
-- STEP 70
DATES
21 'NOV' 1992 /
/
 
-- STEP 71
DATES
1 'DEC' 1992 /
/
 
-- STEP 72
DATES
11 'DEC' 1992 /
/
 
-- STEP 73
DATES
21 'DEC' 1992 /
/
 
-- STEP 74
DATES
31 'DEC' 1992 /
/
 
-- STEP 75
DATES
10 'JAN' 1993 /
/
 
-- STEP 76
DATES
20 'JAN' 1993 /
/
 
-- STEP 77
DATES
30 'JAN' 1993 /
/
 
-- STEP 78
DATES
9 'FEB' 1993 /
/
 
-- STEP 79
DATES
19 'FEB' 1993 /
/
 
-- STEP 80
DATES
1 'MAR' 1993 /
/
 
-- STEP 81
DATES
11 'MAR' 1993 /
/
 
-- STEP 82
DATES
21 'MAR' 1993 /
/
 
-- STEP 83
DATES
31 'MAR' 1993 /
/
 
-- STEP 84
DATES
10 'APR' 1993 /
/
 
-- STEP 85
DATES
20 'APR' 1993 /
/
 
-- STEP 86
DATES
30 'APR' 1993 /
/
 
-- STEP 87
DATES
10 'MAY' 1993 /
/
 
-- STEP 88
DATES
20 'MAY' 1993 /
/
 
-- STEP 89
DATES
30 'MAY' 1993 /
/
 
-- STEP 90
DATES
9 'JUN' 1993 /
/
 
-- STEP 91
DATES
19 'JUN' 1993 /
/
 
-- STEP 92
DATES
29 'JUN' 1993 /
/
 
-- STEP 93
DATES
9 'JUL' 1993 /
/
 
-- STEP 94
DATES
19 'JUL' 1993 /
/
 
-- STEP 95
DATES
29 'JUL' 1993 /
/
 
-- STEP 96
DATES
8 'AUG' 1993 /
/
 
-- STEP 97
DATES
18 'AUG' 1993 /
/
 
-- STEP 98
DATES
28 'AUG' 1993 /
/
 
-- STEP 99
DATES
7 'SEP' 1993 /
/
 
-- STEP 100
DATES
17 'SEP' 1993 /
/
 
-- STEP 101
DATES
27 'SEP' 1993 /
/
 
-- STEP 102
DATES
7 'OCT' 1993 /
/
 
-- STEP 103
DATES
17 'OCT' 1993 /
/
 
-- STEP 104
DATES
27 'OCT' 1993 /
/
 
-- STEP 105
DATES
6 'NOV' 1993 /
/
 
-- STEP 106
DATES
16 'NOV' 1993 /
/
 
-- STEP 107
DATES
26 'NOV' 1993 /
/
 
-- STEP 108
DATES
6 'DEC' 1993 /
/
 
-- STEP 109
DATES
16 'DEC' 1993 /
/
 
-- STEP 110
DATES
26 'DEC' 1993 /
/
 
-- STEP 111
DATES
5 'JAN' 1994 /
/
 
-- STEP 112
DATES
15 'JAN' 1994 /
/
 
-- STEP 113
DATES
25 'JAN' 1994 /
/
 
-- STEP 114
DATES
4 'FEB' 1994 /
/
 
-- STEP 115
DATES
14 'FEB' 1994 /
/
 
-- STEP 116
DATES
24 'FEB' 1994 /
/
 
-- STEP 117
DATES
6 'MAR' 1994 /
/
 
-- STEP 118
DATES
16 'MAR' 1994 /
/
 
-- STEP 119
DATES
26 'MAR' 1994 /
/
 
-- STEP 120
DATES
5 'APR' 1994 /
/
 
-- STEP 121
DATES
15 'APR' 1994 /
/
 
-- STEP 122
DATES
25 'APR' 1994 /
/
 
-- STEP 123
DATES
5 'MAY' 1994 /
/
 
-- STEP 124
DATES
15 'MAY' 1994 /
/
 
-- STEP 125
DATES
25 'MAY' 1994 /
/
 
-- STEP 126
DATES
4 'JUN' 1994 /
/
 
-- STEP 127
DATES
14 'JUN' 1994 /
/
 
-- STEP 128
DATES
24 'JUN' 1994 /
/
 
-- STEP 129
DATES
4 'JUL' 1994 /
/
 
-- STEP 130
DATES
14 'JUL' 1994 /
/
 
-- STEP 131
DATES
24 'JUL' 1994 /
/
 
-- STEP 132
DATES
3 'AUG' 1994 /
/
 
-- STEP 133
DATES
13 'AUG' 1994 /
/
 
-- STEP 134
DATES
23 'AUG' 1994 /
/
 
-- STEP 135
DATES
2 'SEP' 1994 /
/
 
-- STEP 136
DATES
12 'SEP' 1994 /
/
 
-- STEP 137
DATES
22 'SEP' 1994 /
/
 
-- STEP 138
DATES
2 'OCT' 1994 /
/
 
-- STEP 139
DATES
12 'OCT' 1994 /
/
 
-- STEP 140
DATES
22 'OCT' 1994 /
/
 
-- STEP 141
DATES
1 'NOV' 1994 /
/
 
-- STEP 142
DATES
11 'NOV' 1994 /
/
 
-- STEP 143
DATES
21 'NOV' 1994 /
/
 
-- STEP 144
DATES
1 'DEC' 1994 /
/
 
-- STEP 145
DATES
11 'DEC' 1994 /
/
 
-- STEP 146
DATES
21 'DEC' 1994 /
/
 
-- STEP 147
DATES
31 'DEC' 1994 /
/
 
-- STEP 148
DATES
10 'JAN' 1995 /
/
 
-- STEP 149
DATES
20 'JAN' 1995 /
/
 
-- STEP 150
DATES
30 'JAN' 1995 /
/
 
-- STEP 151
DATES
9 'FEB' 1995 /
/
 
-- STEP 152
DATES
19 'FEB' 1995 /
/
 
-- STEP 153
DATES
1 'MAR' 1995 /
/
 
-- STEP 154
DATES
11 'MAR' 1995 /
/
 
-- STEP 155
DATES
21 'MAR' 1995 /
/
 
-- STEP 156
DATES
31 'MAR' 1995 /
/
 
-- STEP 157
DATES
10 'APR' 1995 /
/
 
-- STEP 158
DATES
20 'APR' 1995 /
/
 
-- STEP 159
DATES
30 'APR' 1995 /
/
 
-- STEP 160
DATES
10 'MAY' 1995 /
/
 
-- STEP 161
DATES
20 'MAY' 1995 /
/
 
-- STEP 162
DATES
30 'MAY' 1995 /
/
 
-- STEP 163
DATES
9 'JUN' 1995 /
/
 
-- STEP 164
DATES
19 'JUN' 1995 /
/
 
-- STEP 165
DATES
29 'JUN' 1995 /
/
 
-- STEP 166
DATES
9 'JUL' 1995 /
/
 
-- STEP 167
DATES
19 'JUL' 1995 /
/
 
-- STEP 168
DATES
29 'JUL' 1995 /
/
 
-- STEP 169
DATES
8 'AUG' 1995 /
/
 
-- STEP 170
DATES
18 'AUG' 1995 /
/
 
-- STEP 171
DATES
28 'AUG' 1995 /
/
 
-- STEP 172
DATES
7 'SEP' 1995 /
/
 
-- STEP 173
DATES
17 'SEP' 1995 /
/
 
-- STEP 174
DATES
27 'SEP' 1995 /
/
 
-- STEP 175
DATES
7 'OCT' 1995 /
/
 
-- STEP 176
DATES
17 'OCT' 1995 /
/
 
-- STEP 177
DATES
27 'OCT' 1995 /
/
 
-- STEP 178
DATES
6 'NOV' 1995 /
/
 
-- STEP 179
DATES
16 'NOV' 1995 /
/
 
-- STEP 180
DATES
26 'NOV' 1995 /
/
 
-- STEP 181
DATES
6 'DEC' 1995 /
/
 
-- STEP 182
DATES
16 'DEC' 1995 /
/
 
-- STEP 183
DATES
26 'DEC' 1995 /
/
 
-- STEP 184
DATES
5 'JAN' 1996 /
/
 
-- STEP 185
DATES
15 'JAN' 1996 /
/
 
-- STEP 186
DATES
25 'JAN' 1996 /
/
 
-- STEP 187
DATES
4 'FEB' 1996 /
/
 
-- STEP 188
DATES
14 'FEB' 1996 /
/
 
-- STEP 189
DATES
24 'FEB' 1996 /
/
 
-- STEP 190
DATES
5 'MAR' 1996 /
/
 
-- STEP 191
DATES
15 'MAR' 1996 /
/
 
-- STEP 192
DATES
25 'MAR' 1996 /
/
 
-- STEP 193
DATES
4 'APR' 1996 /
/
 
-- STEP 194
DATES
14 'APR' 1996 /
/
 
-- STEP 195
DATES
24 'APR' 1996 /
/
 
-- STEP 196
DATES
4 'MAY' 1996 /
/
 
-- STEP 197
DATES
14 'MAY' 1996 /
/
 
-- STEP 198
DATES
24 'MAY' 1996 /
/
 
-- STEP 199
DATES
3 'JUN' 1996 /
/
 
-- STEP 200
DATES
13 'JUN' 1996 /
/
 
-- STEP 201
DATES
23 'JUN' 1996 /
/
 
-- STEP 202
DATES
3 'JUL' 1996 /
/
 
-- STEP 203
DATES
13 'JUL' 1996 /
/
 
-- STEP 204
DATES
23 'JUL' 1996 /
/
 
-- STEP 205
DATES
2 'AUG' 1996 /
/
 
-- STEP 206
DATES
12 'AUG' 1996 /
/
 
-- STEP 207
DATES
22 'AUG' 1996 /
/
 
-- STEP 208
DATES
1 'SEP' 1996 /
/
 
-- STEP 209
DATES
11 'SEP' 1996 /
/
 
-- STEP 210
DATES
21 'SEP' 1996 /
/
 
-- STEP 211
DATES
1 'OCT' 1996 /
/
 
-- STEP 212
DATES
11 'OCT' 1996 /
/
 
-- STEP 213
DATES
21 'OCT' 1996 /
/
 
-- STEP 214
DATES
31 'OCT' 1996 /
/
 
-- STEP 215
DATES
10 'NOV' 1996 /
/
 
-- STEP 216
DATES
20 'NOV' 1996 /
/
 
-- STEP 217
DATES
30 'NOV' 1996 /
/
 
-- STEP 218
DATES
10 'DEC' 1996 /
/
 
-- STEP 219
DATES
20 'DEC' 1996 /
/
 
-- STEP 220
DATES
30 'DEC' 1996 /
/
 
-- STEP 221
DATES
9 'JAN' 1997 /
/
 
-- STEP 222
DATES
19 'JAN' 1997 /
/
 
-- STEP 223
DATES
29 'JAN' 1997 /
/
 
-- STEP 224
DATES
8 'FEB' 1997 /
/
 
-- STEP 225
DATES
18 'FEB' 1997 /
/
 
-- STEP 226
DATES
28 'FEB' 1997 /
/
 
-- STEP 227
DATES
10 'MAR' 1997 /
/
 
-- STEP 228
DATES
20 'MAR' 1997 /
/
 
-- STEP 229
DATES
30 'MAR' 1997 /
/
 
-- STEP 230
DATES
9 'APR' 1997 /
/
 
-- STEP 231
DATES
19 'APR' 1997 /
/
 
-- STEP 232
DATES
29 'APR' 1997 /
/
 
-- STEP 233
DATES
9 'MAY' 1997 /
/
 
-- STEP 234
DATES
19 'MAY' 1997 /
/
 
-- STEP 235
DATES
29 'MAY' 1997 /
/
 
-- STEP 236
DATES
8 'JUN' 1997 /
/
 
-- STEP 237
DATES
18 'JUN' 1997 /
/
 
-- STEP 238
DATES
28 'JUN' 1997 /
/
 
-- STEP 239
DATES
8 'JUL' 1997 /
/
 
-- STEP 240
DATES
18 'JUL' 1997 /
/
 
-- STEP 241
DATES
28 'JUL' 1997 /
/
 
-- STEP 242
DATES
7 'AUG' 1997 /
/
 
-- STEP 243
DATES
17 'AUG' 1997 /
/
 
-- STEP 244
DATES
27 'AUG' 1997 /
/
 
-- STEP 245
DATES
6 'SEP' 1997 /
/
 
-- STEP 246
DATES
16 'SEP' 1997 /
/
 
-- STEP 247
DATES
26 'SEP' 1997 /
/
 
-- STEP 248
DATES
6 'OCT' 1997 /
/
 
-- STEP 249
DATES
16 'OCT' 1997 /
/
 
-- STEP 250
DATES
26 'OCT' 1997 /
/
 
-- STEP 251
DATES
5 'NOV' 1997 /
/
 
-- STEP 252
DATES
15 'NOV' 1997 /
/
 
-- STEP 253
DATES
25 'NOV' 1997 /
/
 
-- STEP 254
DATES
5 'DEC' 1997 /
/
 
-- STEP 255
DATES
15 'DEC' 1997 /
/
 
-- STEP 256
DATES
25 'DEC' 1997 /
/
 
-- STEP 257
DATES
4 'JAN' 1998 /
/
 
-- STEP 258
DATES
14 'JAN' 1998 /
/
 
-- STEP 259
DATES
24 'JAN' 1998 /
/
 
-- STEP 260
DATES
3 'FEB' 1998 /
/
 
-- STEP 261
DATES
13 'FEB' 1998 /
/
 
-- STEP 262
DATES
23 'FEB' 1998 /
/
 
-- STEP 263
DATES
5 'MAR' 1998 /
/
 
-- STEP 264
DATES
15 'MAR' 1998 /
/
 
-- STEP 265
DATES
25 'MAR' 1998 /
/
 
-- STEP 266
DATES
4 'APR' 1998 /
/
 
-- STEP 267
DATES
14 'APR' 1998 /
/
 
-- STEP 268
DATES
24 'APR' 1998 /
/
 
-- STEP 269
DATES
4 'MAY' 1998 /
/
 
-- STEP 270
DATES
14 'MAY' 1998 /
/
 
-- STEP 271
DATES
24 'MAY' 1998 /
/
 
-- STEP 272
DATES
3 'JUN' 1998 /
/
 
-- STEP 273
DATES
13 'JUN' 1998 /
/
 
-- STEP 274
DATES
23 'JUN' 1998 /
/
 
-- STEP 275
DATES
3 'JUL' 1998 /
/
 
-- STEP 276
DATES
13 'JUL' 1998 /
/
 
-- STEP 277
DATES
23 'JUL' 1998 /
/
 
-- STEP 278
DATES
2 'AUG' 1998 /
/
 
-- STEP 279
DATES
12 'AUG' 1998 /
/
 
-- STEP 280
DATES
22 'AUG' 1998 /
/
 
-- STEP 281
DATES
1 'SEP' 1998 /
/
 
-- STEP 282
DATES
11 'SEP' 1998 /
/
 
-- STEP 283
DATES
21 'SEP' 1998 /
/
 
-- STEP 284
DATES
1 'OCT' 1998 /
/
 
-- STEP 285
DATES
11 'OCT' 1998 /
/
 
-- STEP 286
DATES
21 'OCT' 1998 /
/
 
-- STEP 287
DATES
31 'OCT' 1998 /
/
 
-- STEP 288
DATES
10 'NOV' 1998 /
/
 
-- STEP 289
DATES
20 'NOV' 1998 /
/
 
-- STEP 290
DATES
30 'NOV' 1998 /
/
 
-- STEP 291
DATES
10 'DEC' 1998 /
/
 
-- STEP 292
DATES
20 'DEC' 1998 /
/
 
-- STEP 293
DATES
30 'DEC' 1998 /
/
 
-- STEP 294
DATES
9 'JAN' 1999 /
/
 
-- STEP 295
DATES
19 'JAN' 1999 /
/
 
-- STEP 296
DATES
29 'JAN' 1999 /
/
 
-- STEP 297
DATES
8 'FEB' 1999 /
/
 
-- STEP 298
DATES
18 'FEB' 1999 /
/
 
-- STEP 299
DATES
28 'FEB' 1999 /
/
 
-- STEP 300
DATES
10 'MAR' 1999 /
/
 
-- STEP 301
DATES
20 'MAR' 1999 /
/
 
-- STEP 302
DATES
30 'MAR' 1999 /
/
 
-- STEP 303
DATES
9 'APR' 1999 /
/
 
-- STEP 304
DATES
19 'APR' 1999 /
/
 
-- STEP 305
DATES
29 'APR' 1999 /
/
 
-- STEP 306
DATES
9 'MAY' 1999 /
/
 
-- STEP 307
DATES
19 'MAY' 1999 /
/
 
-- STEP 308
DATES
29 'MAY' 1999 /
/
 
-- STEP 309
DATES
8 'JUN' 1999 /
/
 
-- STEP 310
DATES
18 'JUN' 1999 /
/
 
-- STEP 311
DATES
28 'JUN' 1999 /
/
 
-- STEP 312
DATES
8 'JUL' 1999 /
/
 
-- STEP 313
DATES
18 'JUL' 1999 /
/
 
-- STEP 314
DATES
28 'JUL' 1999 /
/
 
-- STEP 315
DATES
7 'AUG' 1999 /
/
 
-- STEP 316
DATES
17 'AUG' 1999 /
/
 
-- STEP 317
DATES
27 'AUG' 1999 /
/
 
-- STEP 318
DATES
6 'SEP' 1999 /
/
 
-- STEP 319
DATES
16 'SEP' 1999 /
/
 
-- STEP 320
DATES
26 'SEP' 1999 /
/
 
-- STEP 321
DATES
6 'OCT' 1999 /
/
 
-- STEP 322
DATES
16 'OCT' 1999 /
/
 
-- STEP 323
DATES
26 'OCT' 1999 /
/
 
-- STEP 324
DATES
5 'NOV' 1999 /
/
 
-- STEP 325
DATES
15 'NOV' 1999 /
/
 
-- STEP 326
DATES
25 'NOV' 1999 /
/
 
-- STEP 327
DATES
5 'DEC' 1999 /
/
 
-- STEP 328
DATES
15 'DEC' 1999 /
/
 
-- STEP 329
DATES
25 'DEC' 1999 /
/
 
-- STEP 330
DATES
4 'JAN' 2000 /
/
 
-- STEP 331
DATES
14 'JAN' 2000 /
/
 
-- STEP 332
DATES
24 'JAN' 2000 /
/
 
-- STEP 333
DATES
3 'FEB' 2000 /
/
 
-- STEP 334
DATES
13 'FEB' 2000 /
/
 
-- STEP 335
DATES
23 'FEB' 2000 /
/
 
-- STEP 336
DATES
4 'MAR' 2000 /
/
 
-- STEP 337
DATES
14 'MAR' 2000 /
/
 
-- STEP 338
DATES
24 'MAR' 2000 /
/
 
-- STEP 339
DATES
3 'APR' 2000 /
/
 
-- STEP 340
DATES
13 'APR' 2000 /
/
 
-- STEP 341
DATES
23 'APR' 2000 /
/
 
-- STEP 342
DATES
3 'MAY' 2000 /
/
 
-- STEP 343
DATES
13 'MAY' 2000 /
/
 
-- STEP 344
DATES
23 'MAY' 2000 /
/
 
-- STEP 345
DATES
2 'JUN' 2000 /
/
 
-- STEP 346
DATES
12 'JUN' 2000 /
/
 
-- STEP 347
DATES
22 'JUN' 2000 /
/
 
-- STEP 348
DATES
2 'JUL' 2000 /
/
 
-- STEP 349
DATES
12 'JUL' 2000 /
/
 
-- STEP 350
DATES
22 'JUL' 2000 /
/
 
-- STEP 351
DATES
1 'AUG' 2000 /
/
 
-- STEP 352
DATES
11 'AUG' 2000 /
/
 
-- STEP 353
DATES
21 'AUG' 2000 /
/
 
-- STEP 354
DATES
31 'AUG' 2000 /
/
 
-- STEP 355
DATES
10 'SEP' 2000 /
/
 
-- STEP 356
DATES
20 'SEP' 2000 /
/
 
-- STEP 357
DATES
30 'SEP' 2000 /
/
 
-- STEP 358
DATES
10 'OCT' 2000 /
/
 
-- STEP 359
DATES
20 'OCT' 2000 /
/
 
-- STEP 360
DATES
30 'OCT' 2000 /
/
 
-- STEP 361
DATES
9 'NOV' 2000 /
/
 
-- STEP 362
DATES
19 'NOV' 2000 /
/
 
-- STEP 363
DATES
29 'NOV' 2000 /
/
 
-- STEP 364
DATES
9 'DEC' 2000 /
/
 
-- STEP 365
DATES
19 'DEC' 2000 /
/
 
-- STEP 366
DATES
29 'DEC' 2000 /
/
 
-- STEP 367
DATES
8 'JAN' 2001 /
/
 
-- STEP 368
DATES
18 'JAN' 2001 /
/
 
-- STEP 369
DATES
28 'JAN' 2001 /
/
 
-- STEP 370
DATES
7 'FEB' 2001 /
/
 
-- STEP 371
DATES
17 'FEB' 2001 /
/
 
-- STEP 372
DATES
27 'FEB' 2001 /
/
 
-- STEP 373
DATES
9 'MAR' 2001 /
/
 
-- STEP 374
DATES
19 'MAR' 2001 /
/
 
-- STEP 375
DATES
29 'MAR' 2001 /
/
 
-- STEP 376
DATES
8 'APR' 2001 /
/
 
-- STEP 377
DATES
18 'APR' 2001 /
/
 
-- STEP 378
DATES
28 'APR' 2001 /
/
 
-- STEP 379
DATES
8 'MAY' 2001 /
/
 
-- STEP 380
DATES
18 'MAY' 2001 /
/
 
-- STEP 381
DATES
28 'MAY' 2001 /
/
 
-- STEP 382
DATES
7 'JUN' 2001 /
/
 
-- STEP 383
DATES
17 'JUN' 2001 /
/
 
-- STEP 384
DATES
27 'JUN' 2001 /
/
 
-- STEP 385
DATES
7 'JUL' 2001 /
/
 
-- STEP 386
DATES
17 'JUL' 2001 /
/
 
-- STEP 387
DATES
27 'JUL' 2001 /
/
 
-- STEP 388
DATES
6 'AUG' 2001 /
/
 
-- STEP 389
DATES
16 'AUG' 2001 /
/
 
-- STEP 390
DATES
26 'AUG' 2001 /
/
 
-- STEP 391
DATES
5 'SEP' 2001 /
/
 
-- STEP 392
DATES
15 'SEP' 2001 /
/
 
-- STEP 393
DATES
25 'SEP' 2001 /
/
 
-- STEP 394
DATES
5 'OCT' 2001 /
/
 
-- STEP 395
DATES
15 'OCT' 2001 /
/
 
-- STEP 396
DATES
25 'OCT' 2001 /
/
 
-- STEP 397
DATES
4 'NOV' 2001 /
/
 
-- STEP 398
DATES
14 'NOV' 2001 /
/
 
-- STEP 399
DATES
24 'NOV' 2001 /
/
 
-- STEP 400
DATES
4 'DEC' 2001 /
/
 
-- STEP 401
DATES
14 'DEC' 2001 /
/
 
-- STEP 402
DATES
24 'DEC' 2001 /
/
 
-- STEP 403
DATES
3 'JAN' 2002 /
/
 
-- STEP 404
DATES
13 'JAN' 2002 /
/
 
-- STEP 405
DATES
23 'JAN' 2002 /
/
 
-- STEP 406
DATES
2 'FEB' 2002 /
/
 
-- STEP 407
DATES
12 'FEB' 2002 /
/
 
-- STEP 408
DATES
22 'FEB' 2002 /
/
 
-- STEP 409
DATES
4 'MAR' 2002 /
/
 
-- STEP 410
DATES
14 'MAR' 2002 /
/
 
-- STEP 411
DATES
24 'MAR' 2002 /
/
 
-- STEP 412
DATES
3 'APR' 2002 /
/
 
-- STEP 413
DATES
13 'APR' 2002 /
/
 
-- STEP 414
DATES
23 'APR' 2002 /
/
 
-- STEP 415
DATES
3 'MAY' 2002 /
/
 
-- STEP 416
DATES
13 'MAY' 2002 /
/
 
-- STEP 417
DATES
23 'MAY' 2002 /
/
 
-- STEP 418
DATES
2 'JUN' 2002 /
/
 
-- STEP 419
DATES
12 'JUN' 2002 /
/
 
-- STEP 420
DATES
22 'JUN' 2002 /
/
 
-- STEP 421
DATES
2 'JUL' 2002 /
/
 
-- STEP 422
DATES
12 'JUL' 2002 /
/
 
-- STEP 423
DATES
22 'JUL' 2002 /
/
 
-- STEP 424
DATES
1 'AUG' 2002 /
/
 
-- STEP 425
DATES
11 'AUG' 2002 /
/
 
-- STEP 426
DATES
21 'AUG' 2002 /
/
 
-- STEP 427
DATES
31 'AUG' 2002 /
/
 
-- STEP 428
DATES
10 'SEP' 2002 /
/
 
-- STEP 429
DATES
20 'SEP' 2002 /
/
 
-- STEP 430
DATES
30 'SEP' 2002 /
/
 
-- STEP 431
DATES
10 'OCT' 2002 /
/
 
-- STEP 432
DATES
20 'OCT' 2002 /
/
 
-- STEP 433
DATES
30 'OCT' 2002 /
/
 
-- STEP 434
DATES
9 'NOV' 2002 /
/
 
-- STEP 435
DATES
19 'NOV' 2002 /
/
 
-- STEP 436
DATES
29 'NOV' 2002 /
/
 
-- STEP 437
DATES
9 'DEC' 2002 /
/
 
-- STEP 438
DATES
19 'DEC' 2002 /
/
 
-- STEP 439
DATES
29 'DEC' 2002 /
/
 
-- STEP 440
DATES
8 'JAN' 2003 /
/
 
-- STEP 441
DATES
18 'JAN' 2003 /
/
 
-- STEP 442
DATES
28 'JAN' 2003 /
/
 
-- STEP 443
DATES
7 'FEB' 2003 /
/
 
-- STEP 444
DATES
17 'FEB' 2003 /
/
 
-- STEP 445
DATES
27 'FEB' 2003 /
/
 
-- STEP 446
DATES
9 'MAR' 2003 /
/
 
-- STEP 447
DATES
19 'MAR' 2003 /
/
 
-- STEP 448
DATES
29 'MAR' 2003 /
/
 
-- STEP 449
DATES
8 'APR' 2003 /
/
 
-- STEP 450
DATES
18 'APR' 2003 /
/
 
-- STEP 451
DATES
28 'APR' 2003 /
/
 
-- STEP 452
DATES
8 'MAY' 2003 /
/
 
-- STEP 453
DATES
18 'MAY' 2003 /
/
 
-- STEP 454
DATES
28 'MAY' 2003 /
/
 
-- STEP 455
DATES
7 'JUN' 2003 /
/
 
-- STEP 456
DATES
17 'JUN' 2003 /
/
 
-- STEP 457
DATES
27 'JUN' 2003 /
/
 
-- STEP 458
DATES
7 'JUL' 2003 /
/
 
-- STEP 459
DATES
17 'JUL' 2003 /
/
 
-- STEP 460
DATES
27 'JUL' 2003 /
/
 
-- STEP 461
DATES
6 'AUG' 2003 /
/
 
-- STEP 462
DATES
16 'AUG' 2003 /
/
 
-- STEP 463
DATES
26 'AUG' 2003 /
/
 
-- STEP 464
DATES
5 'SEP' 2003 /
/
 
-- STEP 465
DATES
15 'SEP' 2003 /
/
 
-- STEP 466
DATES
25 'SEP' 2003 /
/
 
-- STEP 467
DATES
5 'OCT' 2003 /
/
 
-- STEP 468
DATES
15 'OCT' 2003 /
/
 
-- STEP 469
DATES
25 'OCT' 2003 /
/
 
-- STEP 470
DATES
4 'NOV' 2003 /
/
 
-- STEP 471
DATES
14 'NOV' 2003 /
/
 
-- STEP 472
DATES
24 'NOV' 2003 /
/
 
-- STEP 473
DATES
4 'DEC' 2003 /
/
 
-- STEP 474
DATES
14 'DEC' 2003 /
/
 
-- STEP 475
DATES
24 'DEC' 2003 /
/
 
-- STEP 476
DATES
3 'JAN' 2004 /
/
 
-- STEP 477
DATES
13 'JAN' 2004 /
/
 
-- STEP 478
DATES
23 'JAN' 2004 /
/
 
-- STEP 479
DATES
2 'FEB' 2004 /
/
 
-- STEP 480
DATES
12 'FEB' 2004 /
/
 
-- STEP 481
DATES
22 'FEB' 2004 /
/
 
-- STEP 482
DATES
3 'MAR' 2004 /
/
 
-- STEP 483
DATES
13 'MAR' 2004 /
/
 
-- STEP 484
DATES
23 'MAR' 2004 /
/
 
-- STEP 485
DATES
2 'APR' 2004 /
/
 
-- STEP 486
DATES
12 'APR' 2004 /
/
 
-- STEP 487
DATES
22 'APR' 2004 /
/
 
-- STEP 488
DATES
2 'MAY' 2004 /
/
 
-- STEP 489
DATES
12 'MAY' 2004 /
/
 
-- STEP 490
DATES
22 'MAY' 2004 /
/
 
-- STEP 491
DATES
1 'JUN' 2004 /
/
 
-- STEP 492
DATES
11 'JUN' 2004 /
/
 
-- STEP 493
DATES
21 'JUN' 2004 /
/
 
-- STEP 494
DATES
1 'JUL' 2004 /
/
 
-- STEP 495
DATES
11 'JUL' 2004 /
/
 
-- STEP 496
DATES
21 'JUL' 2004 /
/
 
-- STEP 497
DATES
31 'JUL' 2004 /
/
 
-- STEP 498
DATES
10 'AUG' 2004 /
/
 
-- STEP 499
DATES
20 'AUG' 2004 /
/
 
-- STEP 500
DATES
30 'AUG' 2004 /
/
 
-- STEP 501
DATES
9 'SEP' 2004 /
/
 
-- STEP 502
DATES
19 'SEP' 2004 /
/
 
-- STEP 503
DATES
29 'SEP' 2004 /
/
 
-- STEP 504
DATES
9 'OCT' 2004 /
/
 
-- STEP 505
DATES
19 'OCT' 2004 /
/
 
-- STEP 506
DATES
29 'OCT' 2004 /
/
 
-- STEP 507
DATES
8 'NOV' 2004 /
/
 
-- STEP 508
DATES
18 'NOV' 2004 /
/
 
-- STEP 509
DATES
28 'NOV' 2004 /
/
 
-- STEP 510
DATES
8 'DEC' 2004 /
/
 
-- STEP 511
DATES
18 'DEC' 2004 /
/
 
-- STEP 512
DATES
28 'DEC' 2004 /
/
 
-- STEP 513
DATES
7 'JAN' 2005 /
/
 
-- STEP 514
DATES
17 'JAN' 2005 /
/
 
-- STEP 515
DATES
27 'JAN' 2005 /
/
 
-- STEP 516
DATES
6 'FEB' 2005 /
/
 
-- STEP 517
DATES
16 'FEB' 2005 /
/
 
-- STEP 518
DATES
26 'FEB' 2005 /
/
 
-- STEP 519
DATES
8 'MAR' 2005 /
/
 
-- STEP 520
DATES
18 'MAR' 2005 /
/
 
-- STEP 521
DATES
28 'MAR' 2005 /
/
 
-- STEP 522
DATES
7 'APR' 2005 /
/
 
-- STEP 523
DATES
17 'APR' 2005 /
/
 
-- STEP 524
DATES
27 'APR' 2005 /
/
 
-- STEP 525
DATES
7 'MAY' 2005 /
/
 
-- STEP 526
DATES
17 'MAY' 2005 /
/
 
-- STEP 527
DATES
27 'MAY' 2005 /
/
 
-- STEP 528
DATES
6 'JUN' 2005 /
/
 
-- STEP 529
DATES
16 'JUN' 2005 /
/
 
-- STEP 530
DATES
26 'JUN' 2005 /
/
 
-- STEP 531
DATES
6 'JUL' 2005 /
/
 
-- STEP 532
DATES
16 'JUL' 2005 /
/
 
-- STEP 533
DATES
26 'JUL' 2005 /
/
 
-- STEP 534
DATES
5 'AUG' 2005 /
/
 
-- STEP 535
DATES
15 'AUG' 2005 /
/
 
-- STEP 536
DATES
25 'AUG' 2005 /
/
 
-- STEP 537
DATES
4 'SEP' 2005 /
/
 
-- STEP 538
DATES
14 'SEP' 2005 /
/
 
-- STEP 539
DATES
24 'SEP' 2005 /
/
 
-- STEP 540
DATES
4 'OCT' 2005 /
/
 
-- STEP 541
DATES
14 'OCT' 2005 /
/
 
-- STEP 542
DATES
24 'OCT' 2005 /
/
 
-- STEP 543
DATES
3 'NOV' 2005 /
/
 
-- STEP 544
DATES
13 'NOV' 2005 /
/
 
-- STEP 545
DATES
23 'NOV' 2005 /
/
 
-- STEP 546
DATES
3 'DEC' 2005 /
/
 
-- STEP 547
DATES
13 'DEC' 2005 /
/
 
-- STEP 548
DATES
23 'DEC' 2005 /
/
 
-- STEP 549
DATES
2 'JAN' 2006 /
/
 
-- STEP 550
DATES
12 'JAN' 2006 /
/
 
-- STEP 551
DATES
22 'JAN' 2006 /
/
 
-- STEP 552
DATES
1 'FEB' 2006 /
/
 
-- STEP 553
DATES
11 'FEB' 2006 /
/
 
-- STEP 554
DATES
21 'FEB' 2006 /
/
 
-- STEP 555
DATES
3 'MAR' 2006 /
/
 
-- STEP 556
DATES
13 'MAR' 2006 /
/
 
-- STEP 557
DATES
23 'MAR' 2006 /
/
 
-- STEP 558
DATES
2 'APR' 2006 /
/
 
-- STEP 559
DATES
12 'APR' 2006 /
/
 
-- STEP 560
DATES
22 'APR' 2006 /
/
 
-- STEP 561
DATES
2 'MAY' 2006 /
/
 
-- STEP 562
DATES
12 'MAY' 2006 /
/
 
-- STEP 563
DATES
22 'MAY' 2006 /
/
 
-- STEP 564
DATES
1 'JUN' 2006 /
/
 
-- STEP 565
DATES
11 'JUN' 2006 /
/
 
-- STEP 566
DATES
21 'JUN' 2006 /
/
 
-- STEP 567
DATES
1 'JUL' 2006 /
/
 
-- STEP 568
DATES
11 'JUL' 2006 /
/
 
-- STEP 569
DATES
21 'JUL' 2006 /
/
 
-- STEP 570
DATES
31 'JUL' 2006 /
/
 
-- STEP 571
DATES
10 'AUG' 2006 /
/
 
-- STEP 572
DATES
20 'AUG' 2006 /
/
 
-- STEP 573
DATES
30 'AUG' 2006 /
/
 
-- STEP 574
DATES
9 'SEP' 2006 /
/
 
-- STEP 575
DATES
19 'SEP' 2006 /
/
 
-- STEP 576
DATES
29 'SEP' 2006 /
/
 
-- STEP 577
DATES
9 'OCT' 2006 /
/
 
-- STEP 578
DATES
19 'OCT' 2006 /
/
 
-- STEP 579
DATES
29 'OCT' 2006 /
/
 
-- STEP 580
DATES
8 'NOV' 2006 /
/
 
-- STEP 581
DATES
18 'NOV' 2006 /
/
 
-- STEP 582
DATES
28 'NOV' 2006 /
/
 
-- STEP 583
DATES
8 'DEC' 2006 /
/
 
-- STEP 584
DATES
18 'DEC' 2006 /
/
 
-- STEP 585
DATES
28 'DEC' 2006 /
/
 
-- STEP 586
DATES
7 'JAN' 2007 /
/
 
-- STEP 587
DATES
17 'JAN' 2007 /
/
 
-- STEP 588
DATES
27 'JAN' 2007 /
/
 
-- STEP 589
DATES
6 'FEB' 2007 /
/
 
-- STEP 590
DATES
16 'FEB' 2007 /
/
 
-- STEP 591
DATES
26 'FEB' 2007 /
/
 
-- STEP 592
DATES
8 'MAR' 2007 /
/
 
-- STEP 593
DATES
18 'MAR' 2007 /
/
 
-- STEP 594
DATES
28 'MAR' 2007 /
/
 
-- STEP 595
DATES
7 'APR' 2007 /
/
 
-- STEP 596
DATES
17 'APR' 2007 /
/
 
-- STEP 597
DATES
27 'APR' 2007 /
/
 
-- STEP 598
DATES
7 'MAY' 2007 /
/
 
-- STEP 599
DATES
17 'MAY' 2007 /
/
 
-- STEP 600
DATES
27 'MAY' 2007 /
/
 
-- STEP 601
DATES
6 'JUN' 2007 /
/
 
-- STEP 602
DATES
16 'JUN' 2007 /
/
 
-- STEP 603
DATES
26 'JUN' 2007 /
/
 
-- STEP 604
DATES
6 'JUL' 2007 /
/
 
-- STEP 605
DATES
16 'JUL' 2007 /
/
 
-- STEP 606
DATES
26 'JUL' 2007 /
/
 
-- STEP 607
DATES
5 'AUG' 2007 /
/
 
-- STEP 608
DATES
15 'AUG' 2007 /
/
 
-- STEP 609
DATES
25 'AUG' 2007 /
/
 
-- STEP 610
DATES
4 'SEP' 2007 /
/
 
-- STEP 611
DATES
14 'SEP' 2007 /
/
 
-- STEP 612
DATES
24 'SEP' 2007 /
/
 
-- STEP 613
DATES
4 'OCT' 2007 /
/
 
-- STEP 614
DATES
14 'OCT' 2007 /
/
 
-- STEP 615
DATES
24 'OCT' 2007 /
/
 
-- STEP 616
DATES
3 'NOV' 2007 /
/
 
-- STEP 617
DATES
13 'NOV' 2007 /
/
 
-- STEP 618
DATES
23 'NOV' 2007 /
/
 
-- STEP 619
DATES
3 'DEC' 2007 /
/
 
-- STEP 620
DATES
13 'DEC' 2007 /
/
 
-- STEP 621
DATES
23 'DEC' 2007 /
/
 
-- STEP 622
DATES
2 'JAN' 2008 /
/
 
-- STEP 623
DATES
12 'JAN' 2008 /
/
 
-- STEP 624
DATES
22 'JAN' 2008 /
/
 
-- STEP 625
DATES
1 'FEB' 2008 /
/
 
-- STEP 626
DATES
11 'FEB' 2008 /
/
 
-- STEP 627
DATES
21 'FEB' 2008 /
/
 
-- STEP 628
DATES
2 'MAR' 2008 /
/
 
-- STEP 629
DATES
12 'MAR' 2008 /
/
 
-- STEP 630
DATES
22 'MAR' 2008 /
/
 
-- STEP 631
DATES
1 'APR' 2008 /
/
 
-- STEP 632
DATES
11 'APR' 2008 /
/
 
-- STEP 633
DATES
21 'APR' 2008 /
/
 
-- STEP 634
DATES
1 'MAY' 2008 /
/
 
-- STEP 635
DATES
11 'MAY' 2008 /
/
 
-- STEP 636
DATES
21 'MAY' 2008 /
/
 
-- STEP 637
DATES
31 'MAY' 2008 /
/
 
-- STEP 638
DATES
10 'JUN' 2008 /
/
 
-- STEP 639
DATES
20 'JUN' 2008 /
/
 
-- STEP 640
DATES
30 'JUN' 2008 /
/
 
-- STEP 641
DATES
10 'JUL' 2008 /
/
 
-- STEP 642
DATES
20 'JUL' 2008 /
/
 
-- STEP 643
DATES
30 'JUL' 2008 /
/
 
-- STEP 644
DATES
9 'AUG' 2008 /
/
 
-- STEP 645
DATES
19 'AUG' 2008 /
/
 
-- STEP 646
DATES
29 'AUG' 2008 /
/
 
-- STEP 647
DATES
8 'SEP' 2008 /
/
 
-- STEP 648
DATES
18 'SEP' 2008 /
/
 
-- STEP 649
DATES
28 'SEP' 2008 /
/
 
-- STEP 650
DATES
8 'OCT' 2008 /
/
 
-- STEP 651
DATES
18 'OCT' 2008 /
/
 
-- STEP 652
DATES
28 'OCT' 2008 /
/
 
-- STEP 653
DATES
7 'NOV' 2008 /
/
 
-- STEP 654
DATES
17 'NOV' 2008 /
/
 
-- STEP 655
DATES
27 'NOV' 2008 /
/
 
-- STEP 656
DATES
7 'DEC' 2008 /
/
 
-- STEP 657
DATES
17 'DEC' 2008 /
/
 
-- STEP 658
DATES
27 'DEC' 2008 /
/
 
-- STEP 659
DATES
6 'JAN' 2009 /
/
 
-- STEP 660
DATES
16 'JAN' 2009 /
/
 
-- STEP 661
DATES
26 'JAN' 2009 /
/
 
-- STEP 662
DATES
5 'FEB' 2009 /
/
 
-- STEP 663
DATES
15 'FEB' 2009 /
/
 
-- STEP 664
DATES
25 'FEB' 2009 /
/
 
-- STEP 665
DATES
7 'MAR' 2009 /
/
 
-- STEP 666
DATES
17 'MAR' 2009 /
/
 
-- STEP 667
DATES
27 'MAR' 2009 /
/
 
-- STEP 668
DATES
6 'APR' 2009 /
/
 
-- STEP 669
DATES
16 'APR' 2009 /
/
 
-- STEP 670
DATES
26 'APR' 2009 /
/
 
-- STEP 671
DATES
6 'MAY' 2009 /
/
 
-- STEP 672
DATES
16 'MAY' 2009 /
/
 
-- STEP 673
DATES
26 'MAY' 2009 /
/
 
-- STEP 674
DATES
5 'JUN' 2009 /
/
 
-- STEP 675
DATES
15 'JUN' 2009 /
/
 
-- STEP 676
DATES
25 'JUN' 2009 /
/
 
-- STEP 677
DATES
5 'JUL' 2009 /
/
 
-- STEP 678
DATES
15 'JUL' 2009 /
/
 
-- STEP 679
DATES
25 'JUL' 2009 /
/
 
-- STEP 680
DATES
4 'AUG' 2009 /
/
 
-- STEP 681
DATES
14 'AUG' 2009 /
/
 
-- STEP 682
DATES
24 'AUG' 2009 /
/
 
-- STEP 683
DATES
3 'SEP' 2009 /
/
 
-- STEP 684
DATES
13 'SEP' 2009 /
/
 
-- STEP 685
DATES
23 'SEP' 2009 /
/
 
-- STEP 686
DATES
3 'OCT' 2009 /
/
 
-- STEP 687
DATES
13 'OCT' 2009 /
/
 
-- STEP 688
DATES
23 'OCT' 2009 /
/
 
-- STEP 689
DATES
2 'NOV' 2009 /
/
 
-- STEP 690
DATES
12 'NOV' 2009 /
/
 
-- STEP 691
DATES
22 'NOV' 2009 /
/
 
-- STEP 692
DATES
2 'DEC' 2009 /
/
 
-- STEP 693
DATES
12 'DEC' 2009 /
/
 
-- STEP 694
DATES
22 'DEC' 2009 /
/
 
-- STEP 695
DATES
1 'JAN' 2010 /
/
 
-- STEP 696
DATES
11 'JAN' 2010 /
/
 
-- STEP 697
DATES
21 'JAN' 2010 /
/
 
-- STEP 698
DATES
31 'JAN' 2010 /
/
 
-- STEP 699
DATES
10 'FEB' 2010 /
/
 
-- STEP 700
DATES
20 'FEB' 2010 /
/
 
-- STEP 701
DATES
2 'MAR' 2010 /
/
 
-- STEP 702
DATES
12 'MAR' 2010 /
/
 
-- STEP 703
DATES
22 'MAR' 2010 /
/
 
-- STEP 704
DATES
1 'APR' 2010 /
/
 
-- STEP 705
DATES
11 'APR' 2010 /
/
 
-- STEP 706
DATES
21 'APR' 2010 /
/
 
-- STEP 707
DATES
1 'MAY' 2010 /
/
 
-- STEP 708
DATES
11 'MAY' 2010 /
/
 
-- STEP 709
DATES
21 'MAY' 2010 /
/
 
-- STEP 710
DATES
31 'MAY' 2010 /
/
 
-- STEP 711
DATES
10 'JUN' 2010 /
/
 
-- STEP 712
DATES
20 'JUN' 2010 /
/
 
-- STEP 713
DATES
30 'JUN' 2010 /
/
 
-- STEP 714
DATES
10 'JUL' 2010 /
/
 
-- STEP 715
DATES
20 'JUL' 2010 /
/
 
-- STEP 716
DATES
30 'JUL' 2010 /
/
 
-- STEP 717
DATES
9 'AUG' 2010 /
/
 
-- STEP 718
DATES
19 'AUG' 2010 /
/
 
-- STEP 719
DATES
29 'AUG' 2010 /
/
 
-- STEP 720
DATES
8 'SEP' 2010 /
/
 
-- STEP 721
DATES
18 'SEP' 2010 /
/
 
-- STEP 722
DATES
28 'SEP' 2010 /
/
 
-- STEP 723
DATES
8 'OCT' 2010 /
/
 
-- STEP 724
DATES
18 'OCT' 2010 /
/
 
-- STEP 725
DATES
28 'OCT' 2010 /
/
 
-- STEP 726
DATES
7 'NOV' 2010 /
/
 
-- STEP 727
DATES
17 'NOV' 2010 /
/
 
-- STEP 728
DATES
27 'NOV' 2010 /
/
 
-- STEP 729
DATES
7 'DEC' 2010 /
/
 
-- STEP 730
DATES
17 'DEC' 2010 /
/
 
-- STEP 731
DATES
27 'DEC' 2010 /
/
 
-- STEP 732
DATES
6 'JAN' 2011 /
/
 
-- STEP 733
DATES
16 'JAN' 2011 /
/
 
-- STEP 734
DATES
26 'JAN' 2011 /
/
 
-- STEP 735
DATES
5 'FEB' 2011 /
/
 
-- STEP 736
DATES
15 'FEB' 2011 /
/
 
-- STEP 737
DATES
25 'FEB' 2011 /
/
 
-- STEP 738
DATES
7 'MAR' 2011 /
/
 
-- STEP 739
DATES
17 'MAR' 2011 /
/
 
-- STEP 740
DATES
27 'MAR' 2011 /
/
 
-- STEP 741
DATES
6 'APR' 2011 /
/
 
-- STEP 742
DATES
16 'APR' 2011 /
/
 
-- STEP 743
DATES
26 'APR' 2011 /
/
 
-- STEP 744
DATES
6 'MAY' 2011 /
/
 
-- STEP 745
DATES
16 'MAY' 2011 /
/
 
-- STEP 746
DATES
26 'MAY' 2011 /
/
 
-- STEP 747
DATES
5 'JUN' 2011 /
/
 
-- STEP 748
DATES
15 'JUN' 2011 /
/
 
-- STEP 749
DATES
25 'JUN' 2011 /
/
 
-- STEP 750
DATES
5 'JUL' 2011 /
/
 
-- STEP 751
DATES
15 'JUL' 2011 /
/
 
-- STEP 752
DATES
25 'JUL' 2011 /
/
 
-- STEP 753
DATES
4 'AUG' 2011 /
/
 
-- STEP 754
DATES
14 'AUG' 2011 /
/
 
-- STEP 755
DATES
24 'AUG' 2011 /
/
 
-- STEP 756
DATES
3 'SEP' 2011 /
/
 
-- STEP 757
DATES
13 'SEP' 2011 /
/
 
-- STEP 758
DATES
23 'SEP' 2011 /
/
 
-- STEP 759
DATES
3 'OCT' 2011 /
/
 
-- STEP 760
DATES
13 'OCT' 2011 /
/
 
-- STEP 761
DATES
23 'OCT' 2011 /
/
 
-- STEP 762
DATES
2 'NOV' 2011 /
/
 
-- STEP 763
DATES
12 'NOV' 2011 /
/
 
-- STEP 764
DATES
22 'NOV' 2011 /
/
 
-- STEP 765
DATES
2 'DEC' 2011 /
/
 
-- STEP 766
DATES
12 'DEC' 2011 /
/
 
-- STEP 767
DATES
22 'DEC' 2011 /
/
 
-- STEP 768
DATES
1 'JAN' 2012 /
/
 
-- STEP 769
DATES
11 'JAN' 2012 /
/
 
-- STEP 770
DATES
21 'JAN' 2012 /
/
 
-- STEP 771
DATES
31 'JAN' 2012 /
/
 
-- STEP 772
DATES
10 'FEB' 2012 /
/
 
-- STEP 773
DATES
20 'FEB' 2012 /
/
 
-- STEP 774
DATES
1 'MAR' 2012 /
/
 
-- STEP 775
DATES
11 'MAR' 2012 /
/
 
-- STEP 776
DATES
21 'MAR' 2012 /
/
 
-- STEP 777
DATES
31 'MAR' 2012 /
/
 
-- STEP 778
DATES
10 'APR' 2012 /
/
 
-- STEP 779
DATES
20 'APR' 2012 /
/
 
-- STEP 780
DATES
30 'APR' 2012 /
/
 
-- STEP 781
DATES
10 'MAY' 2012 /
/
 
-- STEP 782
DATES
20 'MAY' 2012 /
/
 
-- STEP 783
DATES
30 'MAY' 2012 /
/
 
-- STEP 784
DATES
9 'JUN' 2012 /
/
 
-- STEP 785
DATES
19 'JUN' 2012 /
/
 
-- STEP 786
DATES
29 'JUN' 2012 /
/
 
-- STEP 787
DATES
9 'JUL' 2012 /
/
 
-- STEP 788
DATES
19 'JUL' 2012 /
/
 
-- STEP 789
DATES
29 'JUL' 2012 /
/
 
-- STEP 790
DATES
8 'AUG' 2012 /
/
 
-- STEP 791
DATES
18 'AUG' 2012 /
/
 
-- STEP 792
DATES
28 'AUG' 2012 /
/
 
-- STEP 793
DATES
7 'SEP' 2012 /
/
 
-- STEP 794
DATES
17 'SEP' 2012 /
/
 
-- STEP 795
DATES
27 'SEP' 2012 /
/
 
-- STEP 796
DATES
7 'OCT' 2012 /
/
 
-- STEP 797
DATES
17 'OCT' 2012 /
/
 
-- STEP 798
DATES
27 'OCT' 2012 /
/
 
-- STEP 799
DATES
6 'NOV' 2012 /
/
 
-- STEP 800
DATES
16 'NOV' 2012 /
/
 
-- STEP 801
DATES
26 'NOV' 2012 /
/
 
-- STEP 802
DATES
6 'DEC' 2012 /
/
 
-- STEP 803
DATES
16 'DEC' 2012 /
/
 
-- STEP 804
DATES
26 'DEC' 2012 /
/
 
-- STEP 805
DATES
5 'JAN' 2013 /
/
 
-- STEP 806
DATES
15 'JAN' 2013 /
/
 
-- STEP 807
DATES
25 'JAN' 2013 /
/
 
-- STEP 808
DATES
4 'FEB' 2013 /
/
 
-- STEP 809
DATES
14 'FEB' 2013 /
/
 
-- STEP 810
DATES
24 'FEB' 2013 /
/
 
-- STEP 811
DATES
6 'MAR' 2013 /
/
 
-- STEP 812
DATES
16 'MAR' 2013 /
/
 
-- STEP 813
DATES
26 'MAR' 2013 /
/
 
-- STEP 814
DATES
5 'APR' 2013 /
/
 
-- STEP 815
DATES
15 'APR' 2013 /
/
 
-- STEP 816
DATES
25 'APR' 2013 /
/
 
-- STEP 817
DATES
5 'MAY' 2013 /
/
 
-- STEP 818
DATES
15 'MAY' 2013 /
/
 
-- STEP 819
DATES
25 'MAY' 2013 /
/
 
-- STEP 820
DATES
4 'JUN' 2013 /
/
 
-- STEP 821
DATES
14 'JUN' 2013 /
/
 
-- STEP 822
DATES
24 'JUN' 2013 /
/
 
-- STEP 823
DATES
4 'JUL' 2013 /
/
 
-- STEP 824
DATES
14 'JUL' 2013 /
/
 
-- STEP 825
DATES
24 'JUL' 2013 /
/
 
-- STEP 826
DATES
3 'AUG' 2013 /
/
 
-- STEP 827
DATES
13 'AUG' 2013 /
/
 
-- STEP 828
DATES
23 'AUG' 2013 /
/
 
-- STEP 829
DATES
2 'SEP' 2013 /
/
 
-- STEP 830
DATES
12 'SEP' 2013 /
/
 
-- STEP 831
DATES
22 'SEP' 2013 /
/
 
-- STEP 832
DATES
2 'OCT' 2013 /
/
 
-- STEP 833
DATES
12 'OCT' 2013 /
/
 
-- STEP 834
DATES
22 'OCT' 2013 /
/
 
-- STEP 835
DATES
1 'NOV' 2013 /
/
 
-- STEP 836
DATES
11 'NOV' 2013 /
/
 
-- STEP 837
DATES
21 'NOV' 2013 /
/
 
-- STEP 838
DATES
1 'DEC' 2013 /
/
 
-- STEP 839
DATES
11 'DEC' 2013 /
/
 
-- STEP 840
DATES
21 'DEC' 2013 /
/
 
-- STEP 841
DATES
31 'DEC' 2013 /
/
 
-- STEP 842
DATES
10 'JAN' 2014 /
/
 
-- STEP 843
DATES
20 'JAN' 2014 /
/
 
-- STEP 844
DATES
30 'JAN' 2014 /
/
 
-- STEP 845
DATES
9 'FEB' 2014 /
/
 
-- STEP 846
DATES
19 'FEB' 2014 /
/
 
-- STEP 847
DATES
1 'MAR' 2014 /
/
 
-- STEP 848
DATES
11 'MAR' 2014 /
/
 
-- STEP 849
DATES
21 'MAR' 2014 /
/
 
-- STEP 850
DATES
31 'MAR' 2014 /
/
 
-- STEP 851
DATES
10 'APR' 2014 /
/
 
-- STEP 852
DATES
20 'APR' 2014 /
/
 
-- STEP 853
DATES
30 'APR' 2014 /
/
 
-- STEP 854
DATES
10 'MAY' 2014 /
/
 
-- STEP 855
DATES
20 'MAY' 2014 /
/
 
-- STEP 856
DATES
30 'MAY' 2014 /
/
 
-- STEP 857
DATES
9 'JUN' 2014 /
/
 
-- STEP 858
DATES
19 'JUN' 2014 /
/
 
-- STEP 859
DATES
29 'JUN' 2014 /
/
 
-- STEP 860
DATES
9 'JUL' 2014 /
/
 
-- STEP 861
DATES
19 'JUL' 2014 /
/
 
-- STEP 862
DATES
29 'JUL' 2014 /
/
 
-- STEP 863
DATES
8 'AUG' 2014 /
/
 
-- STEP 864
DATES
18 'AUG' 2014 /
/
 
-- STEP 865
DATES
28 'AUG' 2014 /
/
 
-- STEP 866
DATES
7 'SEP' 2014 /
/
 
-- STEP 867
DATES
17 'SEP' 2014 /
/
 
-- STEP 868
DATES
27 'SEP' 2014 /
/
 
-- STEP 869
DATES
7 'OCT' 2014 /
/
 
-- STEP 870
DATES
17 'OCT' 2014 /
/
 
-- STEP 871
DATES
27 'OCT' 2014 /
/
 
-- STEP 872
DATES
6 'NOV' 2014 /
/
 
-- STEP 873
DATES
16 'NOV' 2014 /
/
 
-- STEP 874
DATES
26 'NOV' 2014 /
/
 
-- STEP 875
DATES
6 'DEC' 2014 /
/
 
-- STEP 876
DATES
16 'DEC' 2014 /
/
 
-- STEP 877
DATES
26 'DEC' 2014 /
/
 
-- STEP 878
DATES
5 'JAN' 2015 /
/
 
-- STEP 879
DATES
15 'JAN' 2015 /
/
 
-- STEP 880
DATES
25 'JAN' 2015 /
/
 
-- STEP 881
DATES
4 'FEB' 2015 /
/
 
-- STEP 882
DATES
14 'FEB' 2015 /
/
 
-- STEP 883
DATES
24 'FEB' 2015 /
/
 
-- STEP 884
DATES
6 'MAR' 2015 /
/
 
-- STEP 885
DATES
16 'MAR' 2015 /
/
 
-- STEP 886
DATES
26 'MAR' 2015 /
/
 
-- STEP 887
DATES
5 'APR' 2015 /
/
 
-- STEP 888
DATES
15 'APR' 2015 /
/
 
-- STEP 889
DATES
25 'APR' 2015 /
/
 
-- STEP 890
DATES
5 'MAY' 2015 /
/
 
-- STEP 891
DATES
15 'MAY' 2015 /
/
 
-- STEP 892
DATES
25 'MAY' 2015 /
/
 
-- STEP 893
DATES
4 'JUN' 2015 /
/
 
-- STEP 894
DATES
14 'JUN' 2015 /
/
 
-- STEP 895
DATES
24 'JUN' 2015 /
/
 
-- STEP 896
DATES
4 'JUL' 2015 /
/
 
-- STEP 897
DATES
14 'JUL' 2015 /
/
 
-- STEP 898
DATES
24 'JUL' 2015 /
/
 
-- STEP 899
DATES
3 'AUG' 2015 /
/
 
-- STEP 900
DATES
13 'AUG' 2015 /
/
 
-- STEP 901
DATES
23 'AUG' 2015 /
/
 
