-- STEP 1
DATES
19 'OCT' 1982 /
/
 
WELSPECS
'INJECTOR' 'G' 1 1 1* 'OIL' 7* /
'PRODUCER' 'G' 10 10 1* 'OIL' 7* /
 /
  
COMPDAT
'INJECTOR' 1 1 1 1 'OPEN' 2* 0.1524 5* /
'PRODUCER' 10 10 3 3 'OPEN' 2* 0.1524 5* /
 /
  
WCONPROD
'PRODUCER' 'OPEN' 'ORAT' 3179.738 2* 3179.738 1* 68.04573 /
 /
  
WCONINJE
'INJECTOR' 'GAS' 'OPEN' 'RATE' 2831685 2* /
 /
  
-- STEP 2
DATES
18 'NOV' 1982 /
/
 
-- STEP 3
DATES
18 'DEC' 1982 /
/
 
-- STEP 4
DATES
17 'JAN' 1983 /
/
 
-- STEP 5
DATES
16 'FEB' 1983 /
/
 
-- STEP 6
DATES
18 'MAR' 1983 /
/
 
-- STEP 7
DATES
17 'APR' 1983 /
/
 
-- STEP 8
DATES
17 'MAY' 1983 /
/
 
-- STEP 9
DATES
16 'JUN' 1983 /
/
 
-- STEP 10
DATES
16 'JUL' 1983 /
/
 
-- STEP 11
DATES
15 'AUG' 1983 /
/
 
-- STEP 12
DATES
14 'SEP' 1983 /
/
 
-- STEP 13
DATES
14 'OCT' 1983 /
/
 
-- STEP 14
DATES
13 'NOV' 1983 /
/
 
-- STEP 15
DATES
13 'DEC' 1983 /
/
 
-- STEP 16
DATES
12 'JAN' 1984 /
/
 
-- STEP 17
DATES
11 'FEB' 1984 /
/
 
-- STEP 18
DATES
12 'MAR' 1984 /
/
 
-- STEP 19
DATES
11 'APR' 1984 /
/
 
-- STEP 20
DATES
11 'MAY' 1984 /
/
 
-- STEP 21
DATES
10 'JUN' 1984 /
/
 
-- STEP 22
DATES
10 'JUL' 1984 /
/
 
-- STEP 23
DATES
9 'AUG' 1984 /
/
 
-- STEP 24
DATES
8 'SEP' 1984 /
/
 
-- STEP 25
DATES
8 'OCT' 1984 /
/
 
-- STEP 26
DATES
7 'NOV' 1984 /
/
 
-- STEP 27
DATES
7 'DEC' 1984 /
/
 
-- STEP 28
DATES
6 'JAN' 1985 /
/
 
-- STEP 29
DATES
5 'FEB' 1985 /
/
 
-- STEP 30
DATES
7 'MAR' 1985 /
/
 
-- STEP 31
DATES
6 'APR' 1985 /
/
 
-- STEP 32
DATES
6 'MAY' 1985 /
/
 
-- STEP 33
DATES
5 'JUN' 1985 /
/
 
-- STEP 34
DATES
5 'JUL' 1985 /
/
 
-- STEP 35
DATES
4 'AUG' 1985 /
/
 
-- STEP 36
DATES
3 'SEP' 1985 /
/
 
-- STEP 37
DATES
3 'OCT' 1985 /
/
 
-- STEP 38
DATES
2 'NOV' 1985 /
/
 
-- STEP 39
DATES
2 'DEC' 1985 /
/
 
-- STEP 40
DATES
1 'JAN' 1986 /
/
 
-- STEP 41
DATES
31 'JAN' 1986 /
/
 
-- STEP 42
DATES
2 'MAR' 1986 /
/
 
-- STEP 43
DATES
1 'APR' 1986 /
/
 
-- STEP 44
DATES
1 'MAY' 1986 /
/
 
-- STEP 45
DATES
31 'MAY' 1986 /
/
 
-- STEP 46
DATES
30 'JUN' 1986 /
/
 
-- STEP 47
DATES
30 'JUL' 1986 /
/
 
-- STEP 48
DATES
29 'AUG' 1986 /
/
 
-- STEP 49
DATES
28 'SEP' 1986 /
/
 
-- STEP 50
DATES
28 'OCT' 1986 /
/
 
-- STEP 51
DATES
27 'NOV' 1986 /
/
 
-- STEP 52
DATES
27 'DEC' 1986 /
/
 
-- STEP 53
DATES
26 'JAN' 1987 /
/
 
-- STEP 54
DATES
25 'FEB' 1987 /
/
 
-- STEP 55
DATES
27 'MAR' 1987 /
/
 
-- STEP 56
DATES
26 'APR' 1987 /
/
 
-- STEP 57
DATES
26 'MAY' 1987 /
/
 
-- STEP 58
DATES
25 'JUN' 1987 /
/
 
-- STEP 59
DATES
25 'JUL' 1987 /
/
 
-- STEP 60
DATES
24 'AUG' 1987 /
/
 
-- STEP 61
DATES
23 'SEP' 1987 /
/
 
-- STEP 62
DATES
23 'OCT' 1987 /
/
 
-- STEP 63
DATES
22 'NOV' 1987 /
/
 
-- STEP 64
DATES
22 'DEC' 1987 /
/
 
-- STEP 65
DATES
21 'JAN' 1988 /
/
 
-- STEP 66
DATES
20 'FEB' 1988 /
/
 
-- STEP 67
DATES
21 'MAR' 1988 /
/
 
-- STEP 68
DATES
20 'APR' 1988 /
/
 
-- STEP 69
DATES
20 'MAY' 1988 /
/
 
-- STEP 70
DATES
19 'JUN' 1988 /
/
 
-- STEP 71
DATES
19 'JUL' 1988 /
/
 
-- STEP 72
DATES
18 'AUG' 1988 /
/
 
-- STEP 73
DATES
17 'SEP' 1988 /
/
 
-- STEP 74
DATES
17 'OCT' 1988 /
/
 
-- STEP 75
DATES
16 'NOV' 1988 /
/
 
-- STEP 76
DATES
16 'DEC' 1988 /
/
 
-- STEP 77
DATES
15 'JAN' 1989 /
/
 
-- STEP 78
DATES
14 'FEB' 1989 /
/
 
-- STEP 79
DATES
16 'MAR' 1989 /
/
 
-- STEP 80
DATES
15 'APR' 1989 /
/
 
-- STEP 81
DATES
15 'MAY' 1989 /
/
 
-- STEP 82
DATES
14 'JUN' 1989 /
/
 
-- STEP 83
DATES
14 'JUL' 1989 /
/
 
-- STEP 84
DATES
13 'AUG' 1989 /
/
 
-- STEP 85
DATES
12 'SEP' 1989 /
/
 
-- STEP 86
DATES
12 'OCT' 1989 /
/
 
-- STEP 87
DATES
11 'NOV' 1989 /
/
 
-- STEP 88
DATES
11 'DEC' 1989 /
/
 
-- STEP 89
DATES
10 'JAN' 1990 /
/
 
-- STEP 90
DATES
9 'FEB' 1990 /
/
 
-- STEP 91
DATES
11 'MAR' 1990 /
/
 
-- STEP 92
DATES
10 'APR' 1990 /
/
 
-- STEP 93
DATES
10 'MAY' 1990 /
/
 
-- STEP 94
DATES
9 'JUN' 1990 /
/
 
-- STEP 95
DATES
9 'JUL' 1990 /
/
 
-- STEP 96
DATES
8 'AUG' 1990 /
/
 
-- STEP 97
DATES
7 'SEP' 1990 /
/
 
-- STEP 98
DATES
7 'OCT' 1990 /
/
 
-- STEP 99
DATES
6 'NOV' 1990 /
/
 
-- STEP 100
DATES
6 'DEC' 1990 /
/
 
-- STEP 101
DATES
5 'JAN' 1991 /
/
 
-- STEP 102
DATES
4 'FEB' 1991 /
/
 
-- STEP 103
DATES
6 'MAR' 1991 /
/
 
-- STEP 104
DATES
5 'APR' 1991 /
/
 
-- STEP 105
DATES
5 'MAY' 1991 /
/
 
-- STEP 106
DATES
4 'JUN' 1991 /
/
 
-- STEP 107
DATES
4 'JUL' 1991 /
/
 
-- STEP 108
DATES
3 'AUG' 1991 /
/
 
-- STEP 109
DATES
2 'SEP' 1991 /
/
 
-- STEP 110
DATES
2 'OCT' 1991 /
/
 
-- STEP 111
DATES
1 'NOV' 1991 /
/
 
-- STEP 112
DATES
1 'DEC' 1991 /
/
 
-- STEP 113
DATES
31 'DEC' 1991 /
/
 
-- STEP 114
DATES
30 'JAN' 1992 /
/
 
-- STEP 115
DATES
29 'FEB' 1992 /
/
 
-- STEP 116
DATES
30 'MAR' 1992 /
/
 
-- STEP 117
DATES
29 'APR' 1992 /
/
 
-- STEP 118
DATES
29 'MAY' 1992 /
/
 
-- STEP 119
DATES
28 'JUN' 1992 /
/
 
-- STEP 120
DATES
28 'JUL' 1992 /
/
 
-- STEP 121
DATES
27 'AUG' 1992 /
/
 
-- STEP 122
DATES
26 'SEP' 1992 /
/
 
-- STEP 123
DATES
26 'OCT' 1992 /
/
 
