-- STEP 1
DATES
1 'FEB' 2005 /
/
 
WELSPECS
'I1' '1' 31 111 1* 'WATER' 7* /
'P1' '1' 1 1 1* 'OIL' 7* /
'P2' '1' 60 1 1* 'OIL' 7* /
'P3' '1' 1 220 1* 'OIL' 7* /
'P4' '1' 60 220 1* 'OIL' 7* /
 /
  
COMPDAT
'I1' 31 111 1 1 'OPEN' 2* 0.1524 3* 'Z' 1* /
'P1' 1 1 1 1 'OPEN' 2* 0.1524 3* 'Z' 1* /
'P2' 60 1 1 1 'OPEN' 2* 0.1524 3* 'Z' 1* /
'P3' 1 220 1 1 'OPEN' 2* 0.1524 3* 'Z' 1* /
'P4' 60 220 1 1 'OPEN' 2* 0.1524 3* 'Z' 1* /
 /
  
WCONPROD
'P1' 'OPEN' 'BHP' 5* 272.1829 /
'P2' 'OPEN' 'BHP' 5* 272.1829 /
'P3' 'OPEN' 'BHP' 5* 272.1829 /
'P4' 'OPEN' 'BHP' 5* 272.1829 /
 /
  
WCONINJE
'I1' 'WATER' 'OPEN' 'RATE' 794.9344 1* 680.4573 /
 /
  
-- STEP 2
DATES
2 'FEB' 2005 /
/
 
-- STEP 3
DATES
5 'FEB' 2005 /
/
 
-- STEP 4
DATES
10 'FEB' 2005 /
/
 
-- STEP 5
DATES
20 'FEB' 2005 /
/
 
-- STEP 6
DATES
2 'MAR' 2005 /
/
 
-- STEP 7
DATES
13 'MAR' 2005 /
/
 
-- STEP 8
DATES
24 'MAR' 2005 /
/
 
-- STEP 9
DATES
13 'MAY' 2005 /
/
 
-- STEP 10
DATES
2 'JUL' 2005 /
/
 
-- STEP 11
DATES
21 'AUG' 2005 /
/
 
-- STEP 12
DATES
10 'OCT' 2005 /
/
 
-- STEP 13
DATES
29 'NOV' 2005 /
/
 
-- STEP 14
DATES
18 'JAN' 2006 /
/
 
-- STEP 15
DATES
9 'MAR' 2006 /
/
 
-- STEP 16
DATES
28 'APR' 2006 /
/
 
-- STEP 17
DATES
17 'JUN' 2006 /
/
 
-- STEP 18
DATES
6 'AUG' 2006 /
/
 
-- STEP 19
DATES
25 'SEP' 2006 /
/
 
-- STEP 20
DATES
14 'NOV' 2006 /
/
 
-- STEP 21
DATES
3 'JAN' 2007 /
/
 
-- STEP 22
DATES
22 'FEB' 2007 /
/
 
-- STEP 23
DATES
13 'APR' 2007 /
/
 
-- STEP 24
DATES
2 'JUN' 2007 /
/
 
-- STEP 25
DATES
22 'JUL' 2007 /
/
 
-- STEP 26
DATES
10 'SEP' 2007 /
/
 
-- STEP 27
DATES
30 'OCT' 2007 /
/
 
-- STEP 28
DATES
19 'DEC' 2007 /
/
 
-- STEP 29
DATES
7 'FEB' 2008 /
/
 
-- STEP 30
DATES
28 'MAR' 2008 /
/
 
-- STEP 31
DATES
17 'MAY' 2008 /
/
 
-- STEP 32
DATES
6 'JUL' 2008 /
/
 
-- STEP 33
DATES
25 'AUG' 2008 /
/
 
-- STEP 34
DATES
14 'OCT' 2008 /
/
 
-- STEP 35
DATES
3 'DEC' 2008 /
/
 
-- STEP 36
DATES
22 'JAN' 2009 /
/
 
-- STEP 37
DATES
13 'MAR' 2009 /
/
 
-- STEP 38
DATES
2 'MAY' 2009 /
/
 
-- STEP 39
DATES
21 'JUN' 2009 /
/
 
-- STEP 40
DATES
10 'AUG' 2009 /
/
 
-- STEP 41
DATES
29 'SEP' 2009 /
/
 
-- STEP 42
DATES
18 'NOV' 2009 /
/
 
-- STEP 43
DATES
7 'JAN' 2010 /
/
 
-- STEP 44
DATES
26 'FEB' 2010 /
/
 
-- STEP 45
DATES
17 'APR' 2010 /
/
 
-- STEP 46
DATES
6 'JUN' 2010 /
/
 
-- STEP 47
DATES
26 'JUL' 2010 /
/
 
